name: Android CI

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build_debug_apk:
    name: Build Debug APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Set Up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'oracle'
          cache: gradle

      - name: Cache Gradle Dependencies
        uses: actions/cache@v5
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('android/**/*.gradle*', 'android/**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle

      - name: Cache Android Build Outputs
        uses: actions/cache@v5
        with:
          path: android/app/build
          key: ${{ runner.os }}-build-${{ hashFiles('android/**/*.gradle*', 'android/**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-build

      - name: Set Executable Permission for Gradle Wrapper
        run: chmod +x gradlew
        working-directory: android

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v5
        with:
          working-directory: android
          
      - name: Run Unit Tests
        run: ./gradlew test
        working-directory: android

      - name: Build APK (Debug)
        id: gradle_build_debug
        run: ./gradlew assembleDebug
        working-directory: android

      - name: Upload Debug APK
        uses: actions/upload-artifact@v5
        with:
          name: app-debug
          path: android/app/build/outputs/apk/debug/
